version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    # depends_on:
    #   - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    # depends_on:
    #   - web
